kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.context.name }}
  namespace: {{ .Values.context.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.context.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.context.name }}
    spec:
      nodeSelector:
        kubernetes.io/os: {{ .Values.deployment.nodetype }}
      containers:
      - image: {{ .Values.deployment.image }}
        name: {{ .Values.deployment.image_name }}
 