apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.context.name }}
  namespace: {{ .Values.context.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.context.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.targetPort }}
