apiVersion: v1
kind: Service
metadata:
  name: my_helm_deployment
  namespace: {{ .Values.context.namespace }}

spec:
  type: LoadBalancer
  selector:
    app: my_helm_deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.targetPort }}
